01. DataStructures/02. Stack/Infix Prefix Postfix/01. Infix to Postfix/infixPostfix.cpp

Added code for infix to postfix conversion using stack in C++.

add infixPostfix.cpp

---

02. Algorithms/02. Sorting/02. InsertionSort/Insertion_Sort.c
02. Algorithms/02. Sorting/02. InsertionSort/Insertion_Sort.cpp

#59 
- Insertion_sort.c
- Insertion_sort.cpp

implemented insertion sort using C and C++

---

01. DataStructures/01. Linked List/1. Singly-Linked-List/InterviewBit Questions/01. ReverseLL/solution_in_cpp.cpp

Solved Issue #14 
Added solution of Reverse LL in cpp.

added solution_in_cpp for reverse LL : issue #14 

---

01. DataStructures/02. Stack/Infix Prefix Postfix/02. Infix to Prefix/infixPrefix.cpp

Contributed Infix to Prefix using Stack in C++

Infix to Prefix using Stack in C++

---

02. Algorithms/06. Number Theory/SieveOfEratosthenes.cpp

Sieve of Eratosthenes is used to find the prime numbers till N in O(Nlog(logN)) time complexity, where N is a very large number.

Added Sieve of Eratosthenes

---

02. Algorithms/02. Sorting/03. Selection Sort/Selection_Sort.c
02. Algorithms/02. Sorting/03. Selection Sort/Selection_Sort.cpp

#93 
- Selection_Sort.c
- Selection_Sort.cpp

selection sort using c and c++ added

---

Love Babbar DSA Sheet Solutions/BackTracking/RatInMaze.cpp

Link--> https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1

Issue#101 Added Rat in Maze problem

---

02. Algorithms/02. Sorting/09. Cyclic Sort/CyclicSort.cpp

Cyclic Sort using c++ implimented

---

Love Babbar DSA Sheet Solutions/LinkedList/Remove_Duplicates_from_Unsorted_LL.cpp

@thepranaygupta  Added Solution of a question **Remove Duplicates from unsorted Linked list** in Linked List folder of Love Babber sde sheet
**PR for Hackoctober 2021**

Added Remove_Duplicates_from_Unsorted_LL sol in Love babber sheet

---

01. DataStructures/01. Linked List/1. Singly-Linked-List/InterviewBit Questions/01. ReverseLL/solution.js
01. DataStructures/01. Linked List/1. Singly-Linked-List/InterviewBit Questions/04. Palindrome List GQ/solution.js
01. DataStructures/01. Linked List/1. Singly-Linked-List/InterviewBit Questions/05. Merge Two Sorted List GQ/solution.js
01. DataStructures/01. Linked List/1. Singly-Linked-List/InterviewBit Questions/07. Remove Duplicates From Sorted List- II GQ/solution.js

Added Solutions of 4 link list Interview Questions in Javascript

Added some Interview Bit link list solutions in Javascript

---

01. DataStructures/02. Stack/Infix Prefix Postfix/04. Prefix to Infix/PrefixToInfix.cpp

I have added the code for Prefix to Infix conversion of an expression in C++

Issue #69 --> Added Prefix to Infix in C++

---

Love Babbar DSA Sheet Solutions/Arrays/Trapping Rainwater Problem/README.md

Adding solution of **Trapping Rainwater Problem** under Arrays in **Love Babbar DSA Sheet Solutions**

Adding solution of Trapping Rainwater Problem

---

Love Babbar DSA Sheet Solutions/Graph/Strongly Connected Components/README.md
Love Babbar DSA Sheet Solutions/Graph/Strongly Connected Components/Strongly_Connected_Components.cpp

Added solution (in C++) and explanation to the problem - <b>Strongly Connected Components using Kosaraju algorithm</b> from Love Babbar's DSA Sheet.
This PR is with reference to issue #142

Added Love Babbar DSA Sheet : Strongly Connected Components

---

01. DataStructures/02. Stack/Infix Prefix Postfix/06. Prefix to Postfix/PrefixPostfix.cpp

In this file conversion from prefix to postfix expression is coded in CPP format.

Added prefixToPostfix cpp file

---

01. DataStructures/01. Linked List/1. Singly-Linked-List/InterviewBit Questions/14. Palindrome List/README.md
01. DataStructures/01. Linked List/1. Singly-Linked-List/InterviewBit Questions/14. Palindrome List/palindromeList.cpp

palindrome linked list

---

01. DataStructures/08. Graph/01. BFS Traversal/BFS.cpp
01. DataStructures/08. Graph/01. BFS Traversal/README.md
01. DataStructures/08. Graph/02. DFS Traversal/DFS.cpp
01. DataStructures/08. Graph/02. DFS Traversal/README.md
01. DataStructures/08. Graph/03. Cycle Detection through BFS/README.md
01. DataStructures/08. Graph/03. Cycle Detection through BFS/cycledetectionbfs.cpp
01. DataStructures/08. Graph/03. Cycle Detection through BFS/cycledetectiondfs.cpp

- Included Graph Traversals - BFS and DFS and their solution in CPP in this repository. Fixes #341 
- Included Graph Concept - Cycle Detection through BFS and DFS traversals. Fixes #342

Included Graph Traversals - BFS and DFS 

---

CodeChef DSA Learning series Solutions/Easy Problems to get started/Add Natural Numbers/README.md
CodeChef DSA Learning series Solutions/Easy Problems to get started/Add Natural Numbers/Solution.cpp
CodeChef DSA Learning series Solutions/Easy Problems to get started/Find Me/README.md
CodeChef DSA Learning series Solutions/Easy Problems to get started/Find Me/Solution.cpp
CodeChef DSA Learning series Solutions/Easy Problems to get started/Find Second Larget/README.md
CodeChef DSA Learning series Solutions/Easy Problems to get started/Find Second Larget/Solution.c
CodeChef DSA Learning series Solutions/Easy Problems to get started/Raju and His Trip/README.md
CodeChef DSA Learning series Solutions/Easy Problems to get started/Raju and His Trip/Solution.cpp
CodeChef DSA Learning series Solutions/Easy Problems to get started/Range Odd/README.md
CodeChef DSA Learning series Solutions/Easy Problems to get started/Range Odd/Solution.cpp
CodeChef DSA Learning series Solutions/Easy Problems to get started/Reverse Me/README.md
CodeChef DSA Learning series Solutions/Easy Problems to get started/Reverse Me/Solution.cpp
CodeChef DSA Learning series Solutions/Easy Problems to get started/Reverse Star Pattern/README.md
CodeChef DSA Learning series Solutions/Easy Problems to get started/Reverse Star Pattern/Solution.cpp

Please review this and merge these changes if any error is there in this please let me know.

Added Solutions

---

01. DataStructures/02. Stack/LeetCode Questions/18. Maximum Nesting Depth of the Parentheses #1614/Resources.md
01. DataStructures/02. Stack/LeetCode Questions/18. Maximum Nesting Depth of the Parentheses #1614/solution.cpp

I have created a resource.md file and uploaded the question and solution link in it.
I have also created a solution file in the same folder.
Please tell me if u have any issue so that I can correct it.

Solved the leetcode problem #1614 Maximum Nesting Depth of the Parentheses

---

02. Algorithms/04. Recursion/Problems/01. 509. Fibonacci Number/fibonacci_cache.py

I added a cleaner version of the fibonacci implementation

added cached version of fibonacci

---

02. Algorithms/02. Sorting/DNF Sort/DNF_Sort.java

Created Dutch National Flag (DNF) solution in Java language.
@thepranaygupta Please have a look!
Fixes #373

Implemented DNF_Sort.java

---

02. Algorithms/02. Sorting/11. Bitonic Sort/BitonicSort.cpp

C++ Program for Bitonic Sort.
@thepranaygupta Kindly have a look!
This is my contribution to Hactoberfest 2021!
Fixes #370

BitonicSort.cpp

---

02. Algorithms/03. Searching/02. Binary Search/Binary_Search.py

I added the binary search algorithm that is already there in java, in python.

added binary search in python

---

02. Algorithms/06. Number Theory/Sieve Of Eratosthenes/Sieve_Of_Eratosthenes.py

Added the sieve of ertosthenes in python

added sieve of eratosthenes in python

---

02. Algorithms/02. Sorting/08. Heap Sort/HeapSort.cpp

Heap Sort implementation in C++ language.
@thepranaygupta Contributed to Hactoberfest 2021! Kindly have a look...
Fixes #372

Created Heapsort.cpp

---

02. Algorithms/02. Sorting/07. Radix Sort/RadixSort.cpp

C++ program for Radix Sort.
@thepranaygupta Kindly have a look at it!
Fixes #371

Created RadixSort.cpp program file.

---

CodeChef DSA Learning series Solutions/Easy Problems to get started/Sum Is Everywhere/README.md
CodeChef DSA Learning series Solutions/Easy Problems to get started/Sum Is Everywhere/Solution.cpp
CodeChef DSA Learning series Solutions/Easy Problems to get started/Valid Triangle Or Not/README.md
CodeChef DSA Learning series Solutions/Easy Problems to get started/Valid Triangle Or Not/Solution.cpp

added "sum is everywhere" (a data structure question) solution (in c++)
also added readme file if there are any changes or any improvements needed please let me know

added solution

---

02. Algorithms/03. Searching/01. Linear Search/Linear_Search.py

Linear Search using Python Language.
@thepranaygupta Kindly look into it!
Fixes #363

Linear_Search.py

---

02. Algorithms/06. Number Theory/Ugly_Number/ugly_no.cpp

Added Ugly No Problem fixes #349

---

02. Algorithms/08. Strings/Palindrome String/Palindrome String.cpp

C++ code to check if the string provided is palindrome or not.
@thepranaygupta Sir kindly have a look!
Solves issue #352

Palindrome String.cpp

---

02. Algorithms/08. Strings/Reverse a String/Reverse_String.c

Reverse a string using C language.
@thepranaygupta Sir kindly have a look!
Fixes #359

Reverse_String.c

---

02. Algorithms/04. Recursion/Problems/03.Towers of Hanoi/TowerOfHanoi.py

Implemented Tower of Hanoi puzzle using the recursion function in python program.
@thepranaygupta Sir kindly have a look!
Fixes #360

TowerOfHanoi.py

---

02. Algorithms/03. Searching/01. Linear Search/Linear_Search.cpp

C++ program to implement Linear Search in an array.
@thepranaygupta  Kindly have a look!
Fixes #362

Created Linear_Search.cpp

---

02. Algorithms/01. Arrays/01. Reverse an Array/Reverse_Array.py

Python program to reverse an array.
@thepranaygupta Kindly have a look!
Fixes #365

Created Reverse_Array.py

---

02. Algorithms/04. Recursion/Problems/01. 509. Fibonacci Number/Fibonacci_SeriesUptoN.cpp

Print Fibonacci Series up to n numbers using the C++ programming language.
@thepranaygupta Kindly look into it!
Fixes #367 
This is my contribution to Hactoberfest 2021!

Fibonacci_SeriesUptoN.cpp

---

02. Algorithms/01. Arrays/02. Find the maximum and minimum element in an array/README.md
02. Algorithms/README.md

updated readme files by correcting some minor spelling and grammer mistakes.

Updated README file

---

Love Babbar DSA Sheet Solutions/Searching & Sorting/First And Last Occurrences of x/first_and_last_occurrences_of_x.cpp
Love Babbar DSA Sheet Solutions/Searching & Sorting/Search in Rotated Sorted Array/search_in_rotated_sorted_array.cpp
Love Babbar DSA Sheet Solutions/Searching & Sorting/Value equal to index value/value_equal_to_index.cpp

🌱Added the cpp solution **passing all the test cases as of the date of commit** for problems in the ***searching and sorting*** section of the DSA-sheet by Love Babbar.

🎯Added cpp solution in searching and sorting.

---

LICENSE

A GNU License is proposed. Which help to grow this project.

Proposed: A GNU License

---

Love Babbar DSA Sheet Solutions/LinkedList/MergeSort IN LL/MergeSort.cpp
Love Babbar DSA Sheet Solutions/LinkedList/QuickSort in LL/quick_sort.cpp
Love Babbar DSA Sheet Solutions/LinkedList/palindrome_in_ll.cpp

mergesort in linked list love babbar sheet.

merge sort in ll

---

Love Babbar DSA Sheet Solutions/LinkedList/ADD 1 number to LL/add_one.cpp
Love Babbar DSA Sheet Solutions/LinkedList/k-shorted Doubly LL/doubly.cpp

K-shorted doubly linked list
